
services:
  # Microservicio 1
  microservicio-voucher:
    build:
      context: ./microservicios/Gestion_voucher
      dockerfile: Dockerfile
    container_name: msv-voucher
    ports:
      - "8086:8000"
    networks:
      - laravel_network
    volumes:
      - ./env/msv-finanzas/.env:/var/www/html/.env
    restart: unless-stopped

 

 # Microservicio 2
  microservicio-pagos:
    build:
      context: ./microservicios/Gestion_pagos
      dockerfile: Dockerfile
    container_name: msv-pagos
    ports:
      - "8087:8000"
    networks:
      - laravel_network
    volumes:
      - ./env/msv-pagos/.env:/var/www/html/.env
    restart: unless-stopped



  # Microservicio 3
  microservicio-finanzas:
    build:
      context: ./microservicios/Gestion_finanzas
      dockerfile: Dockerfile  
    container_name: msv-finanzas
    ports:
      - "8088:8000"
    networks:
      - laravel_network
    volumes:
      - ./env/msv-finanzas/.env:/var/www/html/.env
    restart: unless-stopped



networks:
  laravel_network:
    driver: bridge


